name: projet411
services:
    
    mariadb:
        container_name: mariadb
        environment:
            - MARIADB_USER=${LOGIN_BD}
            - MARIADB_PASSWORD=${PASS_BD}
            - MARIADB_DATABASE=${NOM_BD}
            - MARIADB_ROOT_PASSWORD=${PASS_ROOT_BD}
        ports:
            - 3306:3306
        
        image: mariadb

        
        volumes:
            - ./db_data:/var/lib/mysql

        
        
        
        

    php:
        container_name: c_monapache
        ports:
            - ${PORT_WEB}:80
        
        image: lucas12458/monapache

        environment:
            - SERVEUR_BD=${SERVEUR_BD}
            - LOGIN_BD=${LOGIN_BD}
            - PASS_BD=${PASS_BD}
            - NOM_BD=${NOM_BD}



        #volumes:
        #   - ./app/var/www/html
        
        
        
       

    phpmyadmin:
        container_name: c_phpmyadmin
        ports:
            - ${PORT_PHPMYADMIN}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        image: phpmyadmin/phpmyadmin

        
            
        
      
    ubuntu:
        container_name: c_monubuntu
        image: lucas12458/monubuntu
        
